// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr9w24nT2_dzbqIrRYaf9gSuUfehHGE2I',
    appId: '1:813846499004:web:f4b2c816ea1623f4a98ab9',
    messagingSenderId: '813846499004',
    projectId: 'voltmask-90c3a',
    authDomain: 'voltmask-90c3a.firebaseapp.com',
    storageBucket: 'voltmask-90c3a.firebasestorage.app',
    measurementId: 'G-GH64ZYWXHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8sU3htjSkOhW4q0SW2afiaSTu2paORZI',
    appId: '1:813846499004:android:c1bf1cf71b76e7bca98ab9',
    messagingSenderId: '813846499004',
    projectId: 'voltmask-90c3a',
    storageBucket: 'voltmask-90c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaFodlZP3YExZ3LD8uPJrrv2XQCwkcUqw',
    appId: '1:813846499004:ios:c76726a47864e3bea98ab9',
    messagingSenderId: '813846499004',
    projectId: 'voltmask-90c3a',
    storageBucket: 'voltmask-90c3a.firebasestorage.app',
    iosBundleId: 'com.example.tasbeeh',
  );
}
